/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DateFormatDescriptor
import org.openapitools.client.models.Logo
import org.openapitools.client.models.TimeZoneDescriptor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the Visual settings of the YouTrack service.
 *
 * @param id 
 * @param timeZone 
 * @param dateFieldFormat 
 * @param logo 
 * @param dollarType 
 */


interface AppearanceSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "timeZone")
    val timeZone: TimeZoneDescriptor?
    @Json(name = "dateFieldFormat")
    val dateFieldFormat: DateFormatDescriptor?
    @Json(name = "logo")
    val logo: Logo?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

