/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BackupError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the current status of the backup process.
 *
 * @param id 
 * @param backupInProgress 
 * @param backupCancelled 
 * @param backupError 
 * @param dollarType 
 */


interface BackupStatus {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "backupInProgress")
    val backupInProgress: kotlin.Boolean?
    @Json(name = "backupCancelled")
    val backupCancelled: kotlin.Boolean?
    @Json(name = "backupError")
    val backupError: BackupError?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

