/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents an error that appeared during the backup.
 *
 * @param id 
 * @param date 
 * @param errorMessage 
 * @param dollarType 
 */


interface BackupError {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "date")
    val date: kotlin.Long?
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

