/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ArticleAttachment
import org.openapitools.client.models.User
import org.openapitools.client.models.Visibility

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a base article entity.
 *
 * @param id 
 * @param attachments 
 * @param content 
 * @param reporter 
 * @param summary 
 * @param visibility 
 * @param dollarType 
 */


interface BaseArticle {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<ArticleAttachment>?
    @Json(name = "content")
    val content: kotlin.String?
    @Json(name = "reporter")
    val reporter: User?
    @Json(name = "summary")
    val summary: kotlin.String?
    @Json(name = "visibility")
    val visibility: Visibility?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

