/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a set of custom field values in YouTrack.
 *
 * @param id 
 * @param isUpdateable 
 * @param dollarType 
 */


interface Bundle {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "isUpdateable")
    val isUpdateable: kotlin.Boolean?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

