/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AgileColumn
import org.openapitools.client.models.CustomField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Agile board columns settings.
 *
 * @param id 
 * @param `field` 
 * @param columns 
 * @param dollarType 
 */


interface ColumnSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "field")
    val `field`: CustomField?
    @Json(name = "columns")
    val columns: kotlin.collections.List<AgileColumn>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

