/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CustomField
import org.openapitools.client.models.FilterField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a custom field of the issue.
 *
 * @param id 
 * @param presentation 
 * @param name 
 * @param dollarType 
 * @param customField 
 */


data class CustomFilterField (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "presentation")
    override val presentation: kotlin.String? = null,

    @Json(name = "name")
    override val name: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "customField")
    val customField: CustomField? = null

) : FilterField

