/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents date format.
 *
 * @param id 
 * @param presentation 
 * @param pattern 
 * @param datePattern 
 * @param dollarType 
 */


interface DateFormatDescriptor {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "presentation")
    val presentation: kotlin.String?
    @Json(name = "pattern")
    val pattern: kotlin.String?
    @Json(name = "datePattern")
    val datePattern: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

