/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Issue
import org.openapitools.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a vote for duplicates of the issue.
 *
 * @param id 
 * @param issue 
 * @param user 
 * @param dollarType 
 */


interface DuplicateVote {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "issue")
    val issue: Issue?
    @Json(name = "user")
    val user: User?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

