/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * For an article that was imported from another service, this entity represents the reference to the article in the external system.
 *
 * @param id 
 * @param name 
 * @param url 
 * @param key 
 * @param dollarType 
 */


interface ExternalArticle {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "url")
    val url: kotlin.String?
    @Json(name = "key")
    val key: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

