/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ColorCoding
import org.openapitools.client.models.CustomField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Sets a card color based on a value of some custom field.
 *
 * @param id 
 * @param dollarType 
 * @param prototype 
 */


data class FieldBasedColorCoding (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "prototype")
    val prototype: CustomField? = null

) : ColorCoding

