/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DateFormatDescriptor
import org.openapitools.client.models.LocaleDescriptor
import org.openapitools.client.models.TimeZoneDescriptor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the user profile in YouTrack.
 *
 * @param id 
 * @param dateFieldFormat 
 * @param timezone 
 * @param locale 
 * @param dollarType 
 */


interface GeneralUserProfile {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "dateFieldFormat")
    val dateFieldFormat: DateFormatDescriptor?
    @Json(name = "timezone")
    val timezone: TimeZoneDescriptor?
    @Json(name = "locale")
    val locale: LocaleDescriptor?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

