/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WorkItemAttributePrototype
import org.openapitools.client.models.WorkItemType
import org.openapitools.client.models.WorkTimeSettings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents time tracking settings of your server.
 *
 * @param id 
 * @param workItemTypes 
 * @param workTimeSettings 
 * @param attributePrototypes 
 * @param dollarType 
 */


interface GlobalTimeTrackingSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "workItemTypes")
    val workItemTypes: kotlin.collections.List<WorkItemType>?
    @Json(name = "workTimeSettings")
    val workTimeSettings: WorkTimeSettings?
    @Json(name = "attributePrototypes")
    val attributePrototypes: kotlin.collections.List<WorkItemAttributePrototype>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

