/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GogsServer
import org.openapitools.client.models.Project
import org.openapitools.client.models.UserGroup
import org.openapitools.client.models.VcsHostingChangesProcessor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a Gogs integration configured for a project.
 *
 * @param id 
 * @param server 
 * @param project 
 * @param relatedProjects 
 * @param enabled 
 * @param visibleForGroups 
 * @param addComments 
 * @param lookupIssuesInBranchName 
 * @param dollarType 
 * @param path 
 * @param branchSpecification 
 * @param committers 
 */


data class GogsChangesProcessor (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "server")
    val server: GogsServer? = null,

    @Json(name = "project")
    override val project: Project? = null,

    @Json(name = "relatedProjects")
    override val relatedProjects: kotlin.collections.List<Project>? = null,

    @Json(name = "enabled")
    override val enabled: kotlin.Boolean? = null,

    @Json(name = "visibleForGroups")
    override val visibleForGroups: kotlin.collections.List<UserGroup>? = null,

    @Json(name = "addComments")
    override val addComments: kotlin.Boolean? = null,

    @Json(name = "lookupIssuesInBranchName")
    override val lookupIssuesInBranchName: kotlin.Boolean? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "path")
    override val path: kotlin.String? = null,

    @Json(name = "branchSpecification")
    override val branchSpecification: kotlin.String? = null,

    @Json(name = "committers")
    override val committers: UserGroup? = null

) : VcsHostingChangesProcessor

