/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DuplicateVote
import org.openapitools.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents users that have voted for the issue or its duplicates.
 *
 * @param id 
 * @param hasVote 
 * @param original 
 * @param duplicate 
 * @param dollarType 
 */


interface IssueVoters {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "hasVote")
    val hasVote: kotlin.Boolean?
    @Json(name = "original")
    val original: kotlin.collections.List<User>?
    @Json(name = "duplicate")
    val duplicate: kotlin.collections.List<DuplicateVote>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

