/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FieldStyle
import org.openapitools.client.models.Issue
import org.openapitools.client.models.Tag
import org.openapitools.client.models.TagSharingSettings
import org.openapitools.client.models.User
import org.openapitools.client.models.UserGroup
import org.openapitools.client.models.WatchFolderSharingSettings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * <p>Deprecated. Use `Tag` instead.</p>
 *
 * @param id 
 * @param name 
 * @param dollarType 
 * @param owner 
 * @param visibleFor 
 * @param updateableBy 
 * @param readSharingSettings 
 * @param updateSharingSettings 
 * @param issues 
 * @param color 
 * @param untagOnResolve 
 * @param tagSharingSettings 
 */


data class IssueTag (

    @Json(name = "id")
    override val id: kotlin.String? = null,

    @Json(name = "name")
    override val name: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "owner")
    override val owner: User? = null,

    @Json(name = "visibleFor")
    override val visibleFor: UserGroup? = null,

    @Json(name = "updateableBy")
    override val updateableBy: UserGroup? = null,

    @Json(name = "readSharingSettings")
    override val readSharingSettings: WatchFolderSharingSettings? = null,

    @Json(name = "updateSharingSettings")
    override val updateSharingSettings: WatchFolderSharingSettings? = null,

    @Json(name = "issues")
    override val issues: kotlin.collections.List<Issue>? = null,

    @Json(name = "color")
    override val color: FieldStyle? = null,

    @Json(name = "untagOnResolve")
    override val untagOnResolve: kotlin.Boolean? = null,

    @Json(name = "tagSharingSettings")
    override val tagSharingSettings: TagSharingSettings? = null

) : Tag

