/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BaseWorkItem
import org.openapitools.client.models.DurationValue
import org.openapitools.client.models.Issue
import org.openapitools.client.models.User
import org.openapitools.client.models.WorkItemAttribute
import org.openapitools.client.models.WorkItemType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a work item in an issue.
 *
 * @param id 
 * @param dollarType 
 * @param author 
 * @param creator 
 * @param text 
 * @param textPreview 
 * @param type 
 * @param created 
 * @param updated 
 * @param duration 
 * @param date 
 * @param issue 
 * @param attributes 
 */


data class IssueWorkItem (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "author")
    val author: User? = null,

    @Json(name = "creator")
    val creator: User? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "textPreview")
    val textPreview: kotlin.String? = null,

    @Json(name = "type")
    val type: WorkItemType? = null,

    @Json(name = "created")
    val created: kotlin.Long? = null,

    @Json(name = "updated")
    val updated: kotlin.Long? = null,

    @Json(name = "duration")
    val duration: DurationValue? = null,

    @Json(name = "date")
    val date: kotlin.Long? = null,

    @Json(name = "issue")
    val issue: Issue? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.List<WorkItemAttribute>? = null

) : BaseWorkItem

