/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FilterField
import org.openapitools.client.models.SwimlaneValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param `field` 
 * @param defaultCardType 
 * @param propertyValues 
 */


data class IssueBasedSwimlaneSettingsAllOf (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "field")
    val `field`: FilterField? = null,

    @Json(name = "defaultCardType")
    val defaultCardType: SwimlaneValue? = null,

    @Json(name = "values")
    val propertyValues: kotlin.collections.List<SwimlaneValue>? = null

)

