/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FilterField
import org.openapitools.client.models.SwimlaneSettings
import org.openapitools.client.models.SwimlaneValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue's subtasks.
 *
 * @param id 
 * @param enabled 
 * @param dollarType 
 * @param `field` 
 * @param defaultCardType 
 * @param propertyValues 
 */


data class IssueBasedSwimlaneSettings (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "enabled")
    override val enabled: kotlin.Boolean? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "field")
    val `field`: FilterField? = null,

    @Json(name = "defaultCardType")
    val defaultCardType: SwimlaneValue? = null,

    @Json(name = "values")
    val propertyValues: kotlin.collections.List<SwimlaneValue>? = null

) : SwimlaneSettings

