/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the settings of a link type in YouTrack.
 *
 * @param id 
 * @param name 
 * @param localizedName 
 * @param sourceToTarget 
 * @param localizedSourceToTarget 
 * @param targetToSource 
 * @param localizedTargetToSource 
 * @param directed 
 * @param aggregation 
 * @param readOnly 
 * @param dollarType 
 */


interface IssueLinkType {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "localizedName")
    val localizedName: kotlin.String?
    @Json(name = "sourceToTarget")
    val sourceToTarget: kotlin.String?
    @Json(name = "localizedSourceToTarget")
    val localizedSourceToTarget: kotlin.String?
    @Json(name = "targetToSource")
    val targetToSource: kotlin.String?
    @Json(name = "localizedTargetToSource")
    val localizedTargetToSource: kotlin.String?
    @Json(name = "directed")
    val directed: kotlin.Boolean?
    @Json(name = "aggregation")
    val aggregation: kotlin.Boolean?
    @Json(name = "readOnly")
    val readOnly: kotlin.Boolean?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

