/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssueWatcher

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents users that are subscribed to notifications about the issue.
 *
 * @param id 
 * @param hasStar 
 * @param issueWatchers 
 * @param duplicateWatchers 
 * @param dollarType 
 */


interface IssueWatchers {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "hasStar")
    val hasStar: kotlin.Boolean?
    @Json(name = "issueWatchers")
    val issueWatchers: kotlin.collections.List<IssueWatcher>?
    @Json(name = "duplicateWatchers")
    val duplicateWatchers: kotlin.collections.List<IssueWatcher>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

