/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssueFolder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the number of issues in a search result.
 *
 * @param id 
 * @param count 
 * @param unresolvedOnly 
 * @param query 
 * @param folder 
 * @param dollarType 
 */


interface IssueCountResponse {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "count")
    val count: kotlin.Long?
    @Json(name = "unresolvedOnly")
    val unresolvedOnly: kotlin.Boolean?
    @Json(name = "query")
    val query: kotlin.String?
    @Json(name = "folder")
    val folder: IssueFolder?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

