/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents jabber settings for this YouTrack installation.
 *
 * @param id 
 * @param isEnabled 
 * @param host 
 * @param port 
 * @param login 
 * @param serviceName 
 * @param dollarType 
 */


interface JabberSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "isEnabled")
    val isEnabled: kotlin.Boolean?
    @Json(name = "host")
    val host: kotlin.String?
    @Json(name = "port")
    val port: kotlin.Int?
    @Json(name = "login")
    val login: kotlin.String?
    @Json(name = "serviceName")
    val serviceName: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

