/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a language locale that is used in UI.
 *
 * @param id 
 * @param locale 
 * @param language 
 * @param community 
 * @param name 
 * @param dollarType 
 */


interface LocaleDescriptor {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "language")
    val language: kotlin.String?
    @Json(name = "community")
    val community: kotlin.Boolean?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

