/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the notification settings in the profile of the specific user.
 *
 * @param id 
 * @param notifyOnOwnChanges 
 * @param jabberNotificationsEnabled 
 * @param emailNotificationsEnabled 
 * @param mentionNotificationsEnabled 
 * @param duplicateClusterNotificationsEnabled 
 * @param mailboxIntegrationNotificationsEnabled 
 * @param usePlainTextEmails 
 * @param autoWatchOnComment 
 * @param autoWatchOnCreate 
 * @param autoWatchOnVote 
 * @param autoWatchOnUpdate 
 * @param dollarType 
 */


interface NotificationsUserProfile {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "notifyOnOwnChanges")
    val notifyOnOwnChanges: kotlin.Boolean?
    @Json(name = "jabberNotificationsEnabled")
    val jabberNotificationsEnabled: kotlin.Boolean?
    @Json(name = "emailNotificationsEnabled")
    val emailNotificationsEnabled: kotlin.Boolean?
    @Json(name = "mentionNotificationsEnabled")
    val mentionNotificationsEnabled: kotlin.Boolean?
    @Json(name = "duplicateClusterNotificationsEnabled")
    val duplicateClusterNotificationsEnabled: kotlin.Boolean?
    @Json(name = "mailboxIntegrationNotificationsEnabled")
    val mailboxIntegrationNotificationsEnabled: kotlin.Boolean?
    @Json(name = "usePlainTextEmails")
    val usePlainTextEmails: kotlin.Boolean?
    @Json(name = "autoWatchOnComment")
    val autoWatchOnComment: kotlin.Boolean?
    @Json(name = "autoWatchOnCreate")
    val autoWatchOnCreate: kotlin.Boolean?
    @Json(name = "autoWatchOnVote")
    val autoWatchOnVote: kotlin.Boolean?
    @Json(name = "autoWatchOnUpdate")
    val autoWatchOnUpdate: kotlin.Boolean?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

