/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmailSettings
import org.openapitools.client.models.JabberSettings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the Notifications settings of the YouTrack service.
 *
 * @param id 
 * @param emailSettings 
 * @param jabberSettings 
 * @param dollarType 
 */


interface NotificationSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "emailSettings")
    val emailSettings: EmailSettings?
    @Json(name = "jabberSettings")
    val jabberSettings: JabberSettings?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

