/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FilterField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, `project`, `created`,             |`updated`, `tags`, and so on.
 *
 * @param id 
 * @param presentation 
 * @param name 
 * @param dollarType 
 */


data class PredefinedFilterField (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "presentation")
    override val presentation: kotlin.String? = null,

    @Json(name = "name")
    override val name: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null

) : FilterField

