/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ColorCoding
import org.openapitools.client.models.ProjectColor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Lets you set a color for a card based on its project.
 *
 * @param id 
 * @param dollarType 
 * @param projectColors 
 */


data class ProjectBasedColorCoding (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "\$type")
    override val dollarType: kotlin.String? = null,

    @Json(name = "projectColors")
    val projectColors: kotlin.collections.List<ProjectColor>? = null

) : ColorCoding

