/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CustomField
import org.openapitools.client.models.CustomFieldCondition
import org.openapitools.client.models.Project

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents settings for custom fields in a particular project.
 *
 * @param id 
 * @param `field` 
 * @param project 
 * @param canBeEmpty 
 * @param emptyFieldText 
 * @param ordinal 
 * @param isPublic 
 * @param hasRunningJob 
 * @param condition 
 * @param dollarType 
 */


interface ProjectCustomField {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "field")
    val `field`: CustomField?
    @Json(name = "project")
    val project: Project?
    @Json(name = "canBeEmpty")
    val canBeEmpty: kotlin.Boolean?
    @Json(name = "emptyFieldText")
    val emptyFieldText: kotlin.String?
    @Json(name = "ordinal")
    val ordinal: kotlin.Int?
    @Json(name = "isPublic")
    val isPublic: kotlin.Boolean?
    @Json(name = "hasRunningJob")
    val hasRunningJob: kotlin.Boolean?
    @Json(name = "condition")
    val condition: CustomFieldCondition?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

