/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Project
import org.openapitools.client.models.ProjectCustomField
import org.openapitools.client.models.WorkItemProjectAttribute
import org.openapitools.client.models.WorkItemType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents time tracking settings of the project.
 *
 * @param id 
 * @param enabled 
 * @param estimate 
 * @param timeSpent 
 * @param workItemTypes 
 * @param project 
 * @param attributes 
 * @param dollarType 
 */


interface ProjectTimeTrackingSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "enabled")
    val enabled: kotlin.Boolean?
    @Json(name = "estimate")
    val estimate: ProjectCustomField?
    @Json(name = "timeSpent")
    val timeSpent: ProjectCustomField?
    @Json(name = "workItemTypes")
    val workItemTypes: kotlin.collections.List<WorkItemType>?
    @Json(name = "project")
    val project: Project?
    @Json(name = "attributes")
    val attributes: kotlin.collections.List<WorkItemProjectAttribute>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

