/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Issue
import org.openapitools.client.models.User
import org.openapitools.client.models.UserGroup

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param archived 
 * @param createdBy 
 * @param customFields 
 * @param description 
 * @param fromEmail 
 * @param iconUrl 
 * @param issues 
 * @param leader 
 * @param name 
 * @param replyToEmail 
 * @param shortName 
 * @param startingNumber 
 * @param team 
 * @param template 
 */


data class ProjectAllOf (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "archived")
    val archived: kotlin.Boolean? = null,

    @Json(name = "createdBy")
    val createdBy: User? = null,

    @Json(name = "customFields")
    val customFields: kotlin.Any? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "fromEmail")
    val fromEmail: kotlin.String? = null,

    @Json(name = "iconUrl")
    val iconUrl: kotlin.String? = null,

    @Json(name = "issues")
    val issues: kotlin.collections.List<Issue>? = null,

    @Json(name = "leader")
    val leader: User? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "replyToEmail")
    val replyToEmail: kotlin.String? = null,

    @Json(name = "shortName")
    val shortName: kotlin.String? = null,

    @Json(name = "startingNumber")
    val startingNumber: kotlin.Long? = null,

    @Json(name = "team")
    val team: UserGroup? = null,

    @Json(name = "template")
    val template: kotlin.Boolean? = null

)

