/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the Resource Sharing (CORS) configuration of the service.
 *
 * @param id 
 * @param allowedOrigins 
 * @param allowAllOrigins 
 * @param dollarType 
 */


interface RestCorsSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "allowedOrigins")
    val allowedOrigins: kotlin.collections.List<kotlin.String>?
    @Json(name = "allowAllOrigins")
    val allowAllOrigins: kotlin.Boolean?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

