/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssueFolder
import org.openapitools.client.models.Suggestion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the list of search suggestions for the currently entered search query.
 *
 * @param id 
 * @param caret 
 * @param ignoreUnresolvedSetting 
 * @param query 
 * @param suggestions 
 * @param folders 
 * @param dollarType 
 */


interface SearchSuggestions {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "caret")
    val caret: kotlin.Int?
    @Json(name = "ignoreUnresolvedSetting")
    val ignoreUnresolvedSetting: kotlin.Boolean?
    @Json(name = "query")
    val query: kotlin.String?
    @Json(name = "suggestions")
    val suggestions: kotlin.collections.List<Suggestion>?
    @Json(name = "folders")
    val folders: kotlin.collections.List<IssueFolder>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

