/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents query suggestion.
 *
 * @param id 
 * @param completionStart 
 * @param completionEnd 
 * @param matchingStart 
 * @param matchingEnd 
 * @param caret 
 * @param description 
 * @param option 
 * @param prefix 
 * @param suffix 
 * @param group 
 * @param icon 
 * @param auxiliaryIcon 
 * @param className 
 * @param dollarType 
 */


interface Suggestion {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "completionStart")
    val completionStart: kotlin.Int?
    @Json(name = "completionEnd")
    val completionEnd: kotlin.Int?
    @Json(name = "matchingStart")
    val matchingStart: kotlin.Int?
    @Json(name = "matchingEnd")
    val matchingEnd: kotlin.Int?
    @Json(name = "caret")
    val caret: kotlin.Int?
    @Json(name = "description")
    val description: kotlin.String?
    @Json(name = "option")
    val option: kotlin.String?
    @Json(name = "prefix")
    val prefix: kotlin.String?
    @Json(name = "suffix")
    val suffix: kotlin.String?
    @Json(name = "group")
    val group: kotlin.String?
    @Json(name = "icon")
    val icon: kotlin.String?
    @Json(name = "auxiliaryIcon")
    val auxiliaryIcon: kotlin.String?
    @Json(name = "className")
    val className: kotlin.String?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

