/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the System settings that affect core functionality of YouTrack.
 *
 * @param id 
 * @param baseUrl 
 * @param maxUploadFileSize 
 * @param maxExportItems 
 * @param administratorEmail 
 * @param allowStatisticsCollection 
 * @param isApplicationReadOnly 
 * @param dollarType 
 */


interface SystemSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "baseUrl")
    val baseUrl: kotlin.String?
    @Json(name = "maxUploadFileSize")
    val maxUploadFileSize: kotlin.Long?
    @Json(name = "maxExportItems")
    val maxExportItems: kotlin.Int?
    @Json(name = "administratorEmail")
    val administratorEmail: kotlin.String?
    @Json(name = "allowStatisticsCollection")
    val allowStatisticsCollection: kotlin.Boolean?
    @Json(name = "isApplicationReadOnly")
    val isApplicationReadOnly: kotlin.Boolean?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

