/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Issue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param target 
 * @param removed 
 * @param added 
 * @param markup 
 */


data class TextCustomFieldActivityItemAllOf (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "target")
    val target: Issue? = null,

    @Json(name = "removed")
    val removed: kotlin.String? = null,

    @Json(name = "added")
    val added: kotlin.String? = null,

    @Json(name = "markup")
    val markup: kotlin.String? = null

)

