/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a time zone.
 *
 * @param id 
 * @param presentation 
 * @param offset 
 * @param dollarType 
 */


interface TimeZoneDescriptor {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "presentation")
    val presentation: kotlin.String?
    @Json(name = "offset")
    val offset: kotlin.Int?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

