/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Project

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a group of users.
 *
 * @param id 
 * @param name 
 * @param ringId 
 * @param usersCount 
 * @param icon 
 * @param allUsersGroup 
 * @param teamForProject 
 * @param dollarType 
 */


interface UserGroup {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "ringId")
    val ringId: kotlin.String?
    @Json(name = "usersCount")
    val usersCount: kotlin.Long?
    @Json(name = "icon")
    val icon: kotlin.String?
    @Json(name = "allUsersGroup")
    val allUsersGroup: kotlin.Boolean?
    @Json(name = "teamForProject")
    val teamForProject: Project?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

