/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChangesProcessor
import org.openapitools.client.models.Issue
import org.openapitools.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a VCS change linked to an issue.
 *
 * @param id 
 * @param date 
 * @param fetched 
 * @param files 
 * @param author 
 * @param processors 
 * @param text 
 * @param urls 
 * @param version 
 * @param issue 
 * @param state 
 * @param dollarType 
 */


interface VcsChange {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "date")
    val date: kotlin.Long?
    @Json(name = "fetched")
    val fetched: kotlin.Long?
    @Json(name = "files")
    val files: kotlin.Int?
    @Json(name = "author")
    val author: User?
    @Json(name = "processors")
    val processors: kotlin.collections.List<ChangesProcessor>?
    @Json(name = "text")
    val text: kotlin.String?
    @Json(name = "urls")
    val urls: kotlin.collections.List<kotlin.String>?
    @Json(name = "version")
    val version: kotlin.String?
    @Json(name = "issue")
    val issue: Issue?
    @Json(name = "state")
    val state: kotlin.Int?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

