/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param archived 
 * @param releaseDate 
 * @param released 
 */


data class VersionBundleElementAllOf (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "archived")
    val archived: kotlin.Boolean? = null,

    @Json(name = "releaseDate")
    val releaseDate: kotlin.Long? = null,

    @Json(name = "released")
    val released: kotlin.Boolean? = null

)

