/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.User
import org.openapitools.client.models.UserGroup

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Stores users and groups that have access to a tag or a saved search.
 *
 * @param id 
 * @param permittedGroups 
 * @param permittedUsers 
 * @param dollarType 
 */


interface WatchFolderSharingSettings {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "permittedGroups")
    val permittedGroups: kotlin.collections.List<UserGroup>?
    @Json(name = "permittedUsers")
    val permittedUsers: kotlin.collections.List<User>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

