/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WorkItemAttributeValue
import org.openapitools.client.models.WorkItemProjectAttribute

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a work item attribute prototype that is common for all projects. The project-related settings for work item attributes are stored in the `WorkItemProjectAttribute` entities.
 *
 * @param id 
 * @param name 
 * @param instances 
 * @param propertyValues 
 * @param dollarType 
 */


interface WorkItemAttributePrototype {

    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "instances")
    val instances: kotlin.collections.List<WorkItemProjectAttribute>?
    @Json(name = "values")
    val propertyValues: kotlin.collections.List<WorkItemAttributeValue>?
    @Json(name = "\$type")
    val dollarType: kotlin.String?
}

